open System

let generate (i:int) = 
    let numName = "个十百千万"
    let s = string(i)
    let l = s.Length
    let sRev = String.Join("",Seq.rev(s))
    seq {
        $"    case {i}:"
        $"          cout <<\"是{l}位数\" << endl;"
        yield! sRev |> Seq.mapi (fun i c -> $"          cout<<\"{numName.[i]}位数是 {c}\"<<endl;")
        $"          cout << \"倒过来是:{sRev}\"<<endl;"
        "          break;"
    }

let header = """#include <iostream>
using namespace std;
int main()
{
    cout << "请给出一个不多于5位的整数";
    int x;
    cin >> x;
    switch(x) {"""
let footer = """    }
    cout << "Code generated by F#" << endl;
}"""
let content = seq {
    header
    for i in 0..99 do
        yield! generate(i)
    footer}
System.IO.File.WriteAllLines("sb.cpp", content)
